"""036 — Quality Module v2 (all qm_* tables from 86 AA Yarn Mills forms)

Revision ID: 036
Revises: 035
Create Date: 2026-06-13
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "036"
down_revision = "035"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # -------------------------------------------------------------------------
    # 1. Reference / Master tables
    # -------------------------------------------------------------------------
    op.create_table(
        "qm_count_specs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), sa.ForeignKey("mills.id", ondelete="CASCADE"), nullable=False),
        sa.Column("count_ne", sa.Float, nullable=False),
        sa.Column("process_type", sa.String(20), nullable=False),
        sa.Column("tm", sa.Float, nullable=True),
        sa.Column("tpi", sa.Float, nullable=True),
        sa.Column("feed_hank", sa.Float, nullable=True),
        sa.Column("std_delivery_hank", sa.Float, nullable=True),
        sa.Column("nominal_hank", sa.Float, nullable=True),
        sa.Column("csp_target", sa.Float, nullable=True),
        sa.Column("cv_limits_json", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
        sa.UniqueConstraint("mill_id", "count_ne", "process_type", name="uq_qm_count_spec"),
    )
    op.create_index("ix_qm_count_specs_mill_id", "qm_count_specs", ["mill_id"])

    op.create_table(
        "qm_approval_templates",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), sa.ForeignKey("mills.id", ondelete="CASCADE"), nullable=False),
        sa.Column("form_type", sa.String(100), nullable=False),
        sa.Column("department", sa.String(10), nullable=False),
        sa.Column("required_roles_json", postgresql.JSONB, nullable=False),
        sa.Column("sla_hours", sa.Integer, nullable=False, server_default="24"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("mill_id", "form_type", name="uq_qm_approval_template"),
    )
    op.create_index("ix_qm_approval_templates_mill_id", "qm_approval_templates", ["mill_id"])

    op.create_table(
        "qm_form_approvals",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), sa.ForeignKey("mills.id", ondelete="CASCADE"), nullable=False),
        sa.Column("form_type", sa.String(100), nullable=False),
        sa.Column("record_id", sa.String(36), nullable=False),
        sa.Column("approval_level", sa.Integer, nullable=False),
        sa.Column("role_code", sa.String(20), nullable=False),
        sa.Column("employee_id", sa.String(36), nullable=True),
        sa.Column("employee_name", sa.String(200), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_note", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_qm_form_approvals_mill_id", "qm_form_approvals", ["mill_id"])
    op.create_index("ix_qm_form_approvals_record", "qm_form_approvals", ["record_id", "form_type"])

    # -------------------------------------------------------------------------
    # 2. Carding & Blowroom
    # -------------------------------------------------------------------------
    def _ts():
        return [
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        ]

    op.create_table(
        "qm_back_process_allocation",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("lot_id", sa.String(36), sa.ForeignKey("lots.id", ondelete="SET NULL"), nullable=True),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("line_no", sa.String(5), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("total_machines", sa.Integer, nullable=True),
        sa.Column("ratio_pct", sa.Float, nullable=True),
        sa.Column("hank", sa.Float, nullable=True),
        sa.Column("speed", sa.Float, nullable=True),
        sa.Column("delivery_band", sa.String(50), nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_bpa_lot_date", "qm_back_process_allocation", ["lot_no", "date"])
    op.create_index("ix_qm_bpa_mill_id", "qm_back_process_allocation", ["mill_id"])

    op.create_table(
        "qm_carding_waste_study",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("delivery_hank", sa.Float, nullable=True),
        sa.Column("licker_in_speed", sa.Float, nullable=True),
        sa.Column("cylinder_speed", sa.Float, nullable=True),
        sa.Column("flats_speed", sa.Float, nullable=True),
        sa.Column("delivery_speed", sa.Float, nullable=True),
        sa.Column("wing_setting", sa.String(50), nullable=True),
        sa.Column("empty_can_kg", sa.Float, nullable=True),
        sa.Column("sliver_can_gross_kg", sa.Float, nullable=True),
        sa.Column("total_production_kg", sa.Float, nullable=True),
        sa.Column("licker_in2_waste_kg", sa.Float, nullable=True),
        sa.Column("licker_in3_waste_kg", sa.Float, nullable=True),
        sa.Column("flat_strips_kg", sa.Float, nullable=True),
        sa.Column("suction_hood_back_kg", sa.Float, nullable=True),
        sa.Column("suction_hood_front_kg", sa.Float, nullable=True),
        sa.Column("total_wastage_pct", sa.Float, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_crd_waste_lot_mc_date", "qm_carding_waste_study", ["mill_id", "lot_no", "machine_no", "date"])

    op.create_table(
        "qm_carding_cv_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("cotton_type", sa.String(50), nullable=True),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("process", sa.String(50), nullable=True),
        sa.Column("delivery_speed", sa.Float, nullable=True),
        sa.Column("cv_1m", sa.Float, nullable=True),
        sa.Column("cv_2m", sa.Float, nullable=True),
        sa.Column("cv_5m", sa.Float, nullable=True),
        sa.Column("cv_10m", sa.Float, nullable=True),
        sa.Column("cv_20m", sa.Float, nullable=True),
        sa.Column("cv_50m", sa.Float, nullable=True),
        sa.Column("cv_100m", sa.Float, nullable=True),
        sa.Column("within_spec", sa.Boolean, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_crd_cv_lot_mc_date_shift", "qm_carding_cv_record", ["mill_id", "lot_no", "machine_no", "date", "shift_code"])

    op.create_table(
        "qm_carding_wrapping",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("line_no", sa.String(5), nullable=True),
        sa.Column("time_taken", sa.String(10), nullable=True),
        sa.Column("std_hank", sa.Float, nullable=True),
        sa.Column("readings_json", postgresql.JSONB, nullable=True),
        sa.Column("avg_weight", sa.Float, nullable=True),
        sa.Column("actual_hank", sa.Float, nullable=True),
        sa.Column("cv_pct", sa.Float, nullable=True),
        sa.Column("ok_input", sa.Boolean, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_carding_wrapping_mill_id", "qm_carding_wrapping", ["mill_id"])

    op.create_table(
        "qm_carding_dfk_pressure",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("line_no", sa.String(5), nullable=True),
        sa.Column("hank", sa.Float, nullable=True),
        sa.Column("cv_pct", sa.Float, nullable=True),
        sa.Column("dfk_width", sa.Float, nullable=True),
        sa.Column("draft", sa.Float, nullable=True),
        sa.Column("v4min", sa.Float, nullable=True),
        sa.Column("v4max", sa.Float, nullable=True),
        sa.Column("target_pa", sa.Float, nullable=True),
        sa.Column("balancing_pa", sa.Float, nullable=True),
        sa.Column("pa_variation", sa.Float, nullable=True),
        sa.Column("draft_deviation", sa.Float, nullable=True),
        sa.Column("home_start", sa.Float, nullable=True),
        sa.Column("home_slow", sa.Float, nullable=True),
        sa.Column("home_high", sa.Float, nullable=True),
        sa.Column("ccd_nominal", sa.Float, nullable=True),
        sa.Column("ccd_actual", sa.Float, nullable=True),
        sa.Column("cfd_nominal", sa.Float, nullable=True),
        sa.Column("cfd_actual", sa.Float, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_carding_dfk_mill_id", "qm_carding_dfk_pressure", ["mill_id"])

    op.create_table(
        "qm_carding_cfd_check",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("side", sa.String(5), nullable=True),
        sa.Column("carding_line", sa.String(5), nullable=True),
        sa.Column("lot_no", sa.String(50), nullable=True),
        sa.Column("with_mat_rs", sa.Float, nullable=True),
        sa.Column("with_mat_ls", sa.Float, nullable=True),
        sa.Column("without_mat_rs", sa.Float, nullable=True),
        sa.Column("without_mat_ls", sa.Float, nullable=True),
        sa.Column("deviation", sa.Float, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_carding_cfd_mill_id", "qm_carding_cfd_check", ["mill_id"])

    op.create_table(
        "qm_carding_speed_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("card_speed", sa.Float, nullable=True),
        sa.Column("cylinder_speed", sa.Float, nullable=True),
        sa.Column("licker1_speed", sa.Float, nullable=True),
        sa.Column("licker2_speed", sa.Float, nullable=True),
        sa.Column("licker3_speed", sa.Float, nullable=True),
        sa.Column("flats_speed", sa.Float, nullable=True),
        sa.Column("dfk_beater_speed", sa.Float, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_carding_speed_mill_id", "qm_carding_speed_record", ["mill_id"])

    op.create_table(
        "qm_carding_flats_cleaning",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("flats_tops_ok", sa.Boolean, nullable=True),
        sa.Column("doffer_ok", sa.Boolean, nullable=True),
        sa.Column("suction_hood_ok", sa.Boolean, nullable=True),
        sa.Column("comb_box_ok", sa.Boolean, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_carding_flats_mill_id", "qm_carding_flats_cleaning", ["mill_id"])

    op.create_table(
        "qm_daily_wastage",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("line_no", sa.String(5), nullable=False),
        sa.Column("process", sa.String(50), nullable=True),
        sa.Column("production_kg", sa.Float, nullable=True),
        sa.Column("wastage_d1_kg", sa.Float, nullable=True),
        sa.Column("wastage_pct", sa.Float, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_daily_wastage_mill_id", "qm_daily_wastage", ["mill_id"])

    # -------------------------------------------------------------------------
    # 3. Drawing
    # -------------------------------------------------------------------------
    op.create_table(
        "qm_drawing_check",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("cotton_type", sa.String(50), nullable=True),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("side", sa.String(5), nullable=True),
        sa.Column("top_roller_cond", sa.String(20), nullable=True),
        sa.Column("bottom_roller_cond", sa.String(20), nullable=True),
        sa.Column("stripper_cond", sa.String(20), nullable=True),
        sa.Column("draft_zone_clean", sa.Boolean, nullable=True),
        sa.Column("cot_change_ok", sa.Boolean, nullable=True),
        sa.Column("suction_duct_cond", sa.String(20), nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_drawing_check_mill_id", "qm_drawing_check", ["mill_id"])

    op.create_table(
        "qm_cot_roller_change",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("side", sa.String(5), nullable=True),
        sa.Column("time_slot", sa.String(10), nullable=True),
        sa.Column("changed_by", sa.String(100), nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_cot_roller_change_mill_id", "qm_cot_roller_change", ["mill_id"])

    op.create_table(
        "qm_sliver_wrapping",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("process", sa.String(5), nullable=False),
        sa.Column("side", sa.String(5), nullable=True),
        sa.Column("std_hank", sa.Float, nullable=True),
        sa.Column("readings_json", postgresql.JSONB, nullable=True),
        sa.Column("avg_weight", sa.Float, nullable=True),
        sa.Column("actual_hank", sa.Float, nullable=True),
        sa.Column("hank_cv_pct", sa.Float, nullable=True),
        sa.Column("ok_input", sa.Boolean, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_sliver_wrap_key", "qm_sliver_wrapping", ["mill_id", "lot_no", "machine_no", "date", "shift_code", "process"])

    op.create_table(
        "qm_drawing_cv_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("cotton_type", sa.String(50), nullable=True),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("side", sa.String(5), nullable=True),
        sa.Column("process", sa.String(5), nullable=True),
        sa.Column("delivery_speed", sa.Float, nullable=True),
        sa.Column("a_pct", sa.Float, nullable=True),
        sa.Column("cv_pct", sa.Float, nullable=True),
        sa.Column("mcv_pct", sa.Float, nullable=True),
        sa.Column("cv_5cm", sa.Float, nullable=True),
        sa.Column("cv_10cm", sa.Float, nullable=True),
        sa.Column("cv_25cm", sa.Float, nullable=True),
        sa.Column("cv_50cm", sa.Float, nullable=True),
        sa.Column("cv_1m", sa.Float, nullable=True),
        sa.Column("cv_3m", sa.Float, nullable=True),
        sa.Column("cv_5m", sa.Float, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_drawing_cv_mill_id", "qm_drawing_cv_record", ["mill_id"])

    op.create_table(
        "qm_a_pct_check",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("cotton_type", sa.String(50), nullable=True),
        sa.Column("feed_hank", sa.Float, nullable=True),
        sa.Column("process", sa.String(10), nullable=True),
        sa.Column("doubling", sa.Integer, nullable=True),
        sa.Column("delivery_hank", sa.Float, nullable=True),
        sa.Column("readings_json", postgresql.JSONB, nullable=True),
        sa.Column("avg_hank", sa.Float, nullable=True),
        sa.Column("levelling_action_point", sa.Float, nullable=True),
        sa.Column("levelling_intensity", sa.Float, nullable=True),
        sa.Column("a_pct_n_plus", sa.Float, nullable=True),
        sa.Column("a_pct_n_minus", sa.Float, nullable=True),
        sa.Column("within_spec", sa.Boolean, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_a_pct_check_mill_id", "qm_a_pct_check", ["mill_id"])

    op.create_table(
        "qm_draw_monitor_check",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("side", sa.String(5), nullable=True),
        sa.Column("parameters_json", postgresql.JSONB, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_draw_monitor_mill_id", "qm_draw_monitor_check", ["mill_id"])

    op.create_table(
        "qm_drawing_stop_occurrences",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("ends_down", sa.Integer, nullable=True),
        sa.Column("levelling_stops", sa.Integer, nullable=True),
        sa.Column("lapping_stops", sa.Integer, nullable=True),
        sa.Column("jam_web_funnel", sa.Integer, nullable=True),
        sa.Column("jam_coiler_head", sa.Integer, nullable=True),
        sa.Column("can_change", sa.Integer, nullable=True),
        sa.Column("spare_can_missing", sa.Integer, nullable=True),
        sa.Column("can_truck_missing", sa.Integer, nullable=True),
        sa.Column("production_kg", sa.Float, nullable=True),
        sa.Column("efficiency_pct", sa.Float, nullable=True),
        sa.Column("a_pct", sa.Float, nullable=True),
        sa.Column("cv_pct", sa.Float, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_drawing_stop_mill_id", "qm_drawing_stop_occurrences", ["mill_id"])

    op.create_table(
        "qm_drawing_speed_check",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("side", sa.String(5), nullable=True),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("ratio", sa.String(20), nullable=True),
        sa.Column("actual_speed", sa.Float, nullable=True),
        sa.Column("std_speed", sa.Float, nullable=True),
        sa.Column("deviation", sa.Float, nullable=True),
        sa.Column("recheck_ok", sa.Boolean, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_drawing_speed_mill_id", "qm_drawing_speed_check", ["mill_id"])

    op.create_table(
        "qm_can_randomisation_check",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("bd_group_json", postgresql.JSONB, nullable=True),
        sa.Column("fd_group_json", postgresql.JSONB, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_can_rand_mill_id", "qm_can_randomisation_check", ["mill_id"])

    # -------------------------------------------------------------------------
    # 4. Simplex
    # -------------------------------------------------------------------------
    for tbl, cols in [
        ("qm_simplex_check", [
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("cotton_type", sa.String(50), nullable=True),
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("top_roller_cond", sa.String(20), nullable=True),
            sa.Column("bottom_roller_cond", sa.String(20), nullable=True),
            sa.Column("top_clearer_cond", sa.String(20), nullable=True),
            sa.Column("bottom_clearer_cond", sa.String(20), nullable=True),
            sa.Column("flyer_cond", sa.String(20), nullable=True),
            sa.Column("draft_zone_clean", sa.Boolean, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_simplex_hank_test", [
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("cotton_type", sa.String(50), nullable=True),
            sa.Column("process", sa.String(20), nullable=True),
            sa.Column("nominal_hank", sa.Float, nullable=True),
            sa.Column("readings_json", postgresql.JSONB, nullable=True),
            sa.Column("avg_hank", sa.Float, nullable=True),
            sa.Column("actual_hank", sa.Float, nullable=True),
            sa.Column("cv_pct", sa.Float, nullable=True),
            sa.Column("within_spec", sa.Boolean, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_simplex_bobbin_weight", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("ratio", sa.String(20), nullable=True),
            sa.Column("length", sa.Float, nullable=True),
            sa.Column("cap_colour", sa.String(30), nullable=True),
            sa.Column("avg_weight", sa.Float, nullable=True),
            sa.Column("spindle_weights_json", postgresql.JSONB, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_simplex_breakage_study", [
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("cotton_type", sa.String(50), nullable=True),
            sa.Column("process", sa.String(20), nullable=True),
            sa.Column("spl_speed", sa.Float, nullable=True),
            sa.Column("time_start", sa.String(10), nullable=True),
            sa.Column("time_end", sa.String(10), nullable=True),
            sa.Column("duration_hrs", sa.Float, nullable=True),
            sa.Column("feed_hank", sa.Float, nullable=True),
            sa.Column("delivery_hank", sa.Float, nullable=True),
            sa.Column("tpi", sa.Float, nullable=True),
            sa.Column("tm", sa.Float, nullable=True),
            sa.Column("creel_breaks", sa.Integer, nullable=True),
            sa.Column("feed_sliver_exhaust", sa.Integer, nullable=True),
            sa.Column("top_roller_lapping", sa.Integer, nullable=True),
            sa.Column("bottom_roller_lapping", sa.Integer, nullable=True),
            sa.Column("slub_breaks", sa.Integer, nullable=True),
            sa.Column("front_roll_false_twister", sa.Integer, nullable=True),
            sa.Column("flyer_finger_breaks", sa.Integer, nullable=True),
            sa.Column("multiple_end_breaks", sa.Integer, nullable=True),
            sa.Column("other_breaks", sa.Integer, nullable=True),
            sa.Column("total_breaks", sa.Integer, nullable=True),
            sa.Column("active_spindles", sa.Integer, nullable=True),
            sa.Column("breaks_per_100spl_hrs", sa.Float, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_simplex_stretch_pct", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("top_readings_json", postgresql.JSONB, nullable=True),
            sa.Column("bottom_readings_json", postgresql.JSONB, nullable=True),
            sa.Column("avg_stretch_pct", sa.Float, nullable=True),
            sa.Column("within_spec", sa.Boolean, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_simplex_speed_check", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("side", sa.String(5), nullable=True),
            sa.Column("ratio", sa.String(20), nullable=True),
            sa.Column("actual_speed", sa.Float, nullable=True),
            sa.Column("std_speed", sa.Float, nullable=True),
            sa.Column("deviation", sa.Float, nullable=True),
            sa.Column("recheck_ok", sa.Boolean, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_simplex_nozzle_check", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("side", sa.String(5), nullable=True),
            sa.Column("nozzle_guide_ok", sa.Boolean, nullable=True),
            sa.Column("nozzle_pipe_ok", sa.Boolean, nullable=True),
            sa.Column("pipe_position_ok", sa.Boolean, nullable=True),
            sa.Column("air_force_ok", sa.Boolean, nullable=True),
            sa.Column("recheck_ok", sa.Boolean, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
    ]:
        op.create_table(
            tbl,
            sa.Column("id", sa.String(36), primary_key=True),
            sa.Column("mill_id", sa.String(36), nullable=False),
            *cols,
            *_ts(),
        )
        op.create_index(f"ix_{tbl}_mill_id", tbl, ["mill_id"])

    # -------------------------------------------------------------------------
    # 5. Ring Frame
    # -------------------------------------------------------------------------
    for tbl, cols in [
        ("qm_rf_snap_study", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("rf_type", sa.String(30), nullable=True),
            sa.Column("snap_rhs", sa.Integer, nullable=True),
            sa.Column("snap_lhs", sa.Integer, nullable=True),
            sa.Column("snap_total", sa.Integer, nullable=True),
            sa.Column("roving_exhaust_rhs", sa.Integer, nullable=True),
            sa.Column("roving_exhaust_lhs", sa.Integer, nullable=True),
            sa.Column("idle_spindles_total", sa.Integer, nullable=True),
            sa.Column("ohtc_status", sa.String(20), nullable=True),
            sa.Column("reasons", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_traverse_check", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("rhs_gear_end", sa.Float, nullable=True),
            sa.Column("rhs_middle", sa.Float, nullable=True),
            sa.Column("rhs_off_end", sa.Float, nullable=True),
            sa.Column("lhs_gear_end", sa.Float, nullable=True),
            sa.Column("lhs_middle", sa.Float, nullable=True),
            sa.Column("lhs_off_end", sa.Float, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_qc_checklist", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("start_time", sa.String(10), nullable=True),
            sa.Column("end_time", sa.String(10), nullable=True),
            sa.Column("check_items_json", postgresql.JSONB, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_cleaning_check", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("lh_drafting_zone_ok", sa.Boolean, nullable=True),
            sa.Column("lh_front_roller_ok", sa.Boolean, nullable=True),
            sa.Column("lh_middle_roller_ok", sa.Boolean, nullable=True),
            sa.Column("lh_back_roller_ok", sa.Boolean, nullable=True),
            sa.Column("lh_brush_ok", sa.Boolean, nullable=True),
            sa.Column("lh_cradle_ok", sa.Boolean, nullable=True),
            sa.Column("lh_bottom_apron_ok", sa.Boolean, nullable=True),
            sa.Column("rh_drafting_zone_ok", sa.Boolean, nullable=True),
            sa.Column("rh_front_roller_ok", sa.Boolean, nullable=True),
            sa.Column("rh_middle_roller_ok", sa.Boolean, nullable=True),
            sa.Column("rh_back_roller_ok", sa.Boolean, nullable=True),
            sa.Column("rh_brush_ok", sa.Boolean, nullable=True),
            sa.Column("rh_cradle_ok", sa.Boolean, nullable=True),
            sa.Column("rh_bottom_apron_ok", sa.Boolean, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_knee_break_check", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("spindle_tape_cond", sa.String(20), nullable=True),
            sa.Column("knee_break_cond", sa.String(20), nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_monitor_settings", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("model", sa.String(50), nullable=True),
            sa.Column("nominal_count", sa.Float, nullable=True),
            sa.Column("actual_count", sa.Float, nullable=True),
            sa.Column("yarn_pitch_count", sa.Float, nullable=True),
            sa.Column("yarn_weight_per_bobbin", sa.Float, nullable=True),
            sa.Column("std_tpm", sa.Float, nullable=True),
            sa.Column("actual_tpm", sa.Float, nullable=True),
            sa.Column("twist_correction_factor", sa.Float, nullable=True),
            sa.Column("total_draft", sa.Float, nullable=True),
            sa.Column("break_draft", sa.Float, nullable=True),
            sa.Column("speed", sa.Float, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_csp_report", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("ratio", sa.String(20), nullable=True),
            sa.Column("samples_json", postgresql.JSONB, nullable=True),
            sa.Column("avg_csp", sa.Float, nullable=True),
            sa.Column("cv_pct", sa.Float, nullable=True),
            sa.Column("max_csp", sa.Float, nullable=True),
            sa.Column("min_csp", sa.Float, nullable=True),
            sa.Column("tm", sa.Float, nullable=True),
            sa.Column("tpi", sa.Float, nullable=True),
            sa.Column("within_spec", sa.Boolean, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_breakage_study", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("ratio", sa.String(20), nullable=True),
            sa.Column("tm", sa.Float, nullable=True),
            sa.Column("rh", sa.Float, nullable=True),
            sa.Column("duration_hrs", sa.Float, nullable=True),
            sa.Column("rf_summary_json", postgresql.JSONB, nullable=True),
            sa.Column("spindle_grid_json", postgresql.JSONB, nullable=True),
            sa.Column("total_breaks", sa.Integer, nullable=True),
            sa.Column("breaks_per_1000spl_hr", sa.Float, nullable=True),
            sa.Column("overall_breakage_pct", sa.Float, nullable=True),
            sa.Column("repeated_2_6", sa.Integer, nullable=True),
            sa.Column("above_6", sa.Integer, nullable=True),
            sa.Column("traveller_fly", sa.Integer, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_doff_breakage", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("ratio", sa.String(20), nullable=True),
            sa.Column("avg_speed", sa.Float, nullable=True),
            sa.Column("breakage_pct", sa.Float, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_restart_breakage", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("before_doff_total", sa.Integer, nullable=True),
            sa.Column("doff_time_total", sa.Integer, nullable=True),
            sa.Column("after_startup_total", sa.Integer, nullable=True),
            sa.Column("doff_time_mins", sa.Float, nullable=True),
            sa.Column("startup_breakage", sa.Integer, nullable=True),
            sa.Column("before_doff_pct", sa.Float, nullable=True),
            sa.Column("doff_time_pct", sa.Float, nullable=True),
            sa.Column("after_startup_pct", sa.Float, nullable=True),
            sa.Column("total_pct", sa.Float, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_count_test", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("samples_json", postgresql.JSONB, nullable=True),
            sa.Column("avg_count", sa.Float, nullable=True),
            sa.Column("count_cv_pct", sa.Float, nullable=True),
            sa.Column("csp", sa.Float, nullable=True),
            sa.Column("max_count", sa.Float, nullable=True),
            sa.Column("min_count", sa.Float, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_spindle_slippage", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("slip_100_rpm", sa.Integer, nullable=True),
            sa.Column("slip_200_rpm", sa.Integer, nullable=True),
            sa.Column("slip_300_plus_rpm", sa.Integer, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_traveller_loading", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("spindle_no", sa.String(20), nullable=True),
            sa.Column("traveller_type", sa.String(50), nullable=True),
            sa.Column("traveller_weight", sa.String(20), nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_rf_spacer_check", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("side", sa.String(5), nullable=True),
            sa.Column("spacer_size", sa.String(10), nullable=True),
            sa.Column("spacer_colour", sa.String(30), nullable=True),
            sa.Column("missing_spindles_json", postgresql.JSONB, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
    ]:
        op.create_table(
            tbl,
            sa.Column("id", sa.String(36), primary_key=True),
            sa.Column("mill_id", sa.String(36), nullable=False),
            *cols,
            *_ts(),
        )
        op.create_index(f"ix_{tbl}_mill_id", tbl, ["mill_id"])

    # -------------------------------------------------------------------------
    # 6. Auto Coner
    # -------------------------------------------------------------------------
    op.create_table(
        "qm_yarn_faults_uster",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("mill_id", sa.String(36), nullable=False),
        sa.Column("machine_no", sa.String(20), nullable=False),
        sa.Column("drum_no", sa.Integer, nullable=True),
        sa.Column("lot_no", sa.String(50), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("shift_code", sa.String(5), nullable=False),
        sa.Column("count_ne", sa.Float, nullable=True),
        sa.Column("ratio", sa.String(20), nullable=True),
        sa.Column("speed", sa.Float, nullable=True),
        sa.Column("kms", sa.Float, nullable=True),
        sa.Column("yf", sa.Integer, nullable=True),
        sa.Column("n_neps", sa.Integer, nullable=True),
        sa.Column("s_short_thick", sa.Integer, nullable=True),
        sa.Column("l_long_thick", sa.Integer, nullable=True),
        sa.Column("t_thin", sa.Integer, nullable=True),
        sa.Column("x_extreme", sa.Integer, nullable=True),
        sa.Column("pf_periodic", sa.Integer, nullable=True),
        sa.Column("cp", sa.Integer, nullable=True),
        sa.Column("cm", sa.Integer, nullable=True),
        sa.Column("ccp", sa.Integer, nullable=True),
        sa.Column("ccm", sa.Integer, nullable=True),
        sa.Column("dp", sa.Integer, nullable=True),
        sa.Column("dm", sa.Integer, nullable=True),
        sa.Column("cdp", sa.Integer, nullable=True),
        sa.Column("cdm", sa.Integer, nullable=True),
        sa.Column("fd", sa.Integer, nullable=True),
        sa.Column("fl", sa.Integer, nullable=True),
        sa.Column("pp", sa.Integer, nullable=True),
        sa.Column("jp", sa.Integer, nullable=True),
        sa.Column("jm", sa.Integer, nullable=True),
        sa.Column("remarks", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        *_ts(),
    )
    op.create_index("ix_qm_yarn_faults_uster_mill_id", "qm_yarn_faults_uster", ["mill_id"])
    op.create_index("ix_qm_yf_uster_lot_mc_date", "qm_yarn_faults_uster", ["mill_id", "lot_no", "machine_no", "date"])

    for tbl, cols in [
        ("qm_classimat_results", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("group", sa.String(20), nullable=True),
            sa.Column("speed", sa.Float, nullable=True),
            sa.Column("length", sa.Float, nullable=True),
            sa.Column("nsl_matrix_json", postgresql.JSONB, nullable=True),
            sa.Column("thin_t_matrix_json", postgresql.JSONB, nullable=True),
            sa.Column("count_deviation_json", postgresql.JSONB, nullable=True),
            sa.Column("periodic_faults_json", postgresql.JSONB, nullable=True),
            sa.Column("splice_channels_json", postgresql.JSONB, nullable=True),
            sa.Column("imperfections_json", postgresql.JSONB, nullable=True),
            sa.Column("yf_per_100km", sa.Float, nullable=True),
            sa.Column("cv_pct", sa.Float, nullable=True),
            sa.Column("thin_50_pct", sa.Float, nullable=True),
            sa.Column("thick_50_pct", sa.Float, nullable=True),
            sa.Column("neps_200_pct", sa.Float, nullable=True),
            sa.Column("total_ipi", sa.Float, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_bag_faults", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("cone_tip_colour", sa.String(30), nullable=True),
            sa.Column("bag_gross_weight", sa.Float, nullable=True),
            sa.Column("cone_weights_json", postgresql.JSONB, nullable=True),
            sa.Column("avg_cone_wt", sa.Float, nullable=True),
            sa.Column("min_cone_wt", sa.Float, nullable=True),
            sa.Column("max_cone_wt", sa.Float, nullable=True),
            sa.Column("fault_cut_yarn", sa.Boolean, nullable=True),
            sa.Column("fault_out_yarn", sa.Boolean, nullable=True),
            sa.Column("fault_stitch_yarn", sa.Boolean, nullable=True),
            sa.Column("fault_without_sticker", sa.Boolean, nullable=True),
            sa.Column("fault_hand_stain", sa.Boolean, nullable=True),
            sa.Column("fault_shade_variation", sa.Boolean, nullable=True),
            sa.Column("fault_tail_missing", sa.Boolean, nullable=True),
            sa.Column("fault_tail_entanglement", sa.Boolean, nullable=True),
            sa.Column("fault_no_qa_signature", sa.Boolean, nullable=True),
            sa.Column("fault_ribboning", sa.Boolean, nullable=True),
            sa.Column("fault_contamination", sa.Boolean, nullable=True),
            sa.Column("fault_big_cone", sa.Boolean, nullable=True),
            sa.Column("fault_small_cone", sa.Boolean, nullable=True),
            sa.Column("fault_loose_cone", sa.Boolean, nullable=True),
            sa.Column("fault_step_cone", sa.Boolean, nullable=True),
            sa.Column("fault_paper_cone_damage", sa.Boolean, nullable=True),
            sa.Column("fault_printing_missing", sa.Boolean, nullable=True),
            sa.Column("fault_others", sa.Boolean, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_daily_reject_cone", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("drum_no", sa.Integer, nullable=True),
            sa.Column("out_yarn", sa.Integer, nullable=True),
            sa.Column("step_cone", sa.Integer, nullable=True),
            sa.Column("shade_cone", sa.Integer, nullable=True),
            sa.Column("big_cone", sa.Integer, nullable=True),
            sa.Column("small_cone", sa.Integer, nullable=True),
            sa.Column("total_rejected", sa.Integer, nullable=True),
            sa.Column("total_produced", sa.Integer, nullable=True),
            sa.Column("rejection_pct", sa.Float, nullable=True),
            sa.Column("stock_for_rewinding", sa.Integer, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_cone_rejection_report", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("process", sa.String(20), nullable=True),
            sa.Column("shift_data_json", postgresql.JSONB, nullable=True),
            sa.Column("sub_total", sa.Integer, nullable=True),
            sa.Column("grand_total", sa.Integer, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_shade_cone", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("side", sa.String(20), nullable=True),
            sa.Column("shade_cone_count", sa.Integer, nullable=True),
            sa.Column("stock_cone_count", sa.Integer, nullable=True),
            sa.Column("total_shade_cone", sa.Integer, nullable=True),
            sa.Column("total_stock_shade_cone", sa.Integer, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_j_mark_cones", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("process", sa.String(20), nullable=True),
            sa.Column("cone_tip_colour", sa.String(30), nullable=True),
            sa.Column("cone_qty", sa.Integer, nullable=True),
            sa.Column("stock_cone", sa.Integer, nullable=True),
            sa.Column("total", sa.Integer, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_wax_pickup", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("machine_type", sa.String(30), nullable=True),
            sa.Column("drum_wax_data_json", postgresql.JSONB, nullable=True),
            sa.Column("total_wax_consumed", sa.Float, nullable=True),
            sa.Column("total_production", sa.Float, nullable=True),
            sa.Column("overall_wax_pickup_pct", sa.Float, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_splice_strength", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("test_grid_json", postgresql.JSONB, nullable=True),
            sa.Column("splice_pct", sa.Float, nullable=True),
            sa.Column("within_spec", sa.Boolean, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_splice_appearance", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("drum_checks_json", postgresql.JSONB, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_tail_end_check", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("tail_missing_count", sa.Integer, nullable=True),
            sa.Column("tail_end_ok_count", sa.Integer, nullable=True),
            sa.Column("total", sa.Integer, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_drum_break_cradle_lifting", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("machine_data_json", postgresql.JSONB, nullable=True),
            sa.Column("combined_total", sa.Integer, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_wax_rotating_check", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("wax_roller_ok", sa.Boolean, nullable=True),
            sa.Column("wax_washer_plate_ok", sa.Boolean, nullable=True),
            sa.Column("wax_touching_yarn", sa.Boolean, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_drum_adapter_cleaning", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("machine_drum_data_json", postgresql.JSONB, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_uster_clearer_check", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("machine_drum_data_json", postgresql.JSONB, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_lot_runout", [
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("process", sa.String(20), nullable=True),
            sa.Column("ratio", sa.String(20), nullable=True),
            sa.Column("cops_colour", sa.String(30), nullable=True),
            sa.Column("cone_tip_colour", sa.String(30), nullable=True),
            sa.Column("running_date", sa.String(10), nullable=True),
            sa.Column("cops_runout_date", sa.String(10), nullable=True),
            sa.Column("packing_runout_date", sa.String(10), nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_finishing_breaks_study", [
            sa.Column("machine_no", sa.String(20), nullable=False),
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("count_ne", sa.Float, nullable=True),
            sa.Column("process", sa.String(20), nullable=True),
            sa.Column("cotton_type", sa.String(50), nullable=True),
            sa.Column("cone_wt_gms", sa.Float, nullable=True),
            sa.Column("total_cone_wt_kg", sa.Float, nullable=True),
            sa.Column("total_length_mtr", sa.Float, nullable=True),
            sa.Column("entanglement", sa.Integer, nullable=True),
            sa.Column("slough_off", sa.Integer, nullable=True),
            sa.Column("cut_end", sa.Integer, nullable=True),
            sa.Column("yarn_waste", sa.Integer, nullable=True),
            sa.Column("splicing_fault", sa.Integer, nullable=True),
            sa.Column("parallel_yarn", sa.Integer, nullable=True),
            sa.Column("ribboning", sa.Integer, nullable=True),
            sa.Column("slubs", sa.Integer, nullable=True),
            sa.Column("neps_kitties", sa.Integer, nullable=True),
            sa.Column("thick_place", sa.Integer, nullable=True),
            sa.Column("thin_place", sa.Integer, nullable=True),
            sa.Column("other_breaks", sa.Integer, nullable=True),
            sa.Column("total_breaks", sa.Integer, nullable=True),
            sa.Column("breaks_per_lac_mtr", sa.Float, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_uv_light_audit", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("area", sa.String(50), nullable=True),
            sa.Column("lights_available_std", sa.Integer, nullable=False, server_default="24"),
            sa.Column("lights_glowing", sa.Integer, nullable=True),
            sa.Column("lights_not_glowing", sa.Integer, nullable=True),
            sa.Column("area_data_json", postgresql.JSONB, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
    ]:
        op.create_table(
            tbl,
            sa.Column("id", sa.String(36), primary_key=True),
            sa.Column("mill_id", sa.String(36), nullable=False),
            *cols,
            *_ts(),
        )
        op.create_index(f"ix_{tbl}_mill_id", tbl, ["mill_id"])

    # -------------------------------------------------------------------------
    # 7. Packing
    # -------------------------------------------------------------------------
    for tbl, cols in [
        ("qm_pwse_check", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("machine_data_json", postgresql.JSONB, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_blend_test", [
            sa.Column("lot_no", sa.String(50), nullable=False),
            sa.Column("machine_no", sa.String(20), nullable=True),
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("line_no", sa.String(5), nullable=True),
            sa.Column("process", sa.String(20), nullable=True),
            sa.Column("nominal_ratio", sa.String(20), nullable=True),
            sa.Column("tested_weight", sa.Float, nullable=True),
            sa.Column("result_1", sa.Float, nullable=True),
            sa.Column("result_2", sa.Float, nullable=True),
            sa.Column("result_3", sa.Float, nullable=True),
            sa.Column("avg_weight", sa.Float, nullable=True),
            sa.Column("cotton_g", sa.Float, nullable=True),
            sa.Column("polyester_g", sa.Float, nullable=True),
            sa.Column("cotton_pct", sa.Float, nullable=True),
            sa.Column("polyester_pct", sa.Float, nullable=True),
            sa.Column("within_spec", sa.Boolean, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
        ("qm_general_daily_checklist", [
            sa.Column("date", sa.String(10), nullable=False),
            sa.Column("shift_code", sa.String(5), nullable=False),
            sa.Column("department", sa.String(20), nullable=True),
            sa.Column("check_items_json", postgresql.JSONB, nullable=True),
            sa.Column("remarks", sa.Text, nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        ]),
    ]:
        op.create_table(
            tbl,
            sa.Column("id", sa.String(36), primary_key=True),
            sa.Column("mill_id", sa.String(36), nullable=False),
            *cols,
            *_ts(),
        )
        op.create_index(f"ix_{tbl}_mill_id", tbl, ["mill_id"])


def downgrade() -> None:
    tables = [
        # Packing
        "qm_general_daily_checklist", "qm_blend_test", "qm_pwse_check",
        # Auto Coner
        "qm_uv_light_audit", "qm_finishing_breaks_study", "qm_lot_runout",
        "qm_uster_clearer_check", "qm_drum_adapter_cleaning", "qm_wax_rotating_check",
        "qm_drum_break_cradle_lifting", "qm_tail_end_check", "qm_splice_appearance",
        "qm_splice_strength", "qm_wax_pickup", "qm_j_mark_cones", "qm_shade_cone",
        "qm_cone_rejection_report", "qm_daily_reject_cone", "qm_bag_faults",
        "qm_classimat_results", "qm_yarn_faults_uster",
        # Ring Frame
        "qm_rf_spacer_check", "qm_rf_traveller_loading", "qm_rf_spindle_slippage",
        "qm_rf_count_test", "qm_rf_restart_breakage", "qm_rf_doff_breakage",
        "qm_rf_breakage_study", "qm_rf_csp_report", "qm_rf_monitor_settings",
        "qm_rf_knee_break_check", "qm_rf_cleaning_check", "qm_rf_qc_checklist",
        "qm_rf_traverse_check", "qm_rf_snap_study",
        # Simplex
        "qm_simplex_nozzle_check", "qm_simplex_speed_check", "qm_simplex_stretch_pct",
        "qm_simplex_breakage_study", "qm_simplex_bobbin_weight", "qm_simplex_hank_test",
        "qm_simplex_check",
        # Drawing
        "qm_can_randomisation_check", "qm_drawing_speed_check", "qm_drawing_stop_occurrences",
        "qm_draw_monitor_check", "qm_a_pct_check", "qm_drawing_cv_record",
        "qm_sliver_wrapping", "qm_cot_roller_change", "qm_drawing_check",
        # Carding
        "qm_daily_wastage", "qm_carding_flats_cleaning", "qm_carding_speed_record",
        "qm_carding_cfd_check", "qm_carding_dfk_pressure", "qm_carding_wrapping",
        "qm_carding_cv_record", "qm_carding_waste_study", "qm_back_process_allocation",
        # Master
        "qm_form_approvals", "qm_approval_templates", "qm_count_specs",
    ]
    for tbl in tables:
        op.drop_table(tbl)
