/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppStoresRouteImport } from './routes/_app.stores'
import { Route as AppStockRouteImport } from './routes/_app.stock'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppQualityRouteImport } from './routes/_app.quality'
import { Route as AppPurchaseRouteImport } from './routes/_app.purchase'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProductionRouteImport } from './routes/_app.production'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppMastersRouteImport } from './routes/_app.masters'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppLotracRouteImport } from './routes/_app.lotrac'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppDispatchRouteImport } from './routes/_app.dispatch'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppCompanyBillingRouteImport } from './routes/_app.company.billing'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminPlansRouteImport } from './routes/_app.admin.plans'
import { Route as AppAdminOrganizationsRouteImport } from './routes/_app.admin.organizations'
import { Route as AppAdminModulesRouteImport } from './routes/_app.admin.modules'
import { Route as AppAdminMillsRouteImport } from './routes/_app.admin.mills'
import { Route as AppAdminLimitsRouteImport } from './routes/_app.admin.limits'
import { Route as AppAdminCompaniesRouteImport } from './routes/_app.admin.companies'
import { Route as AppAdminColumnConfigRouteImport } from './routes/_app.admin.column-config'
import { Route as AppAdminBillingRouteImport } from './routes/_app.admin.billing'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'
import { Route as AppAdminArchiveRouteImport } from './routes/_app.admin.archive'
import { Route as AppAdminBillingSubscriptionsRouteImport } from './routes/_app.admin.billing.subscriptions'
import { Route as AppAdminBillingPlansRouteImport } from './routes/_app.admin.billing.plans'
import { Route as AppAdminBillingPaymentsRouteImport } from './routes/_app.admin.billing.payments'
import { Route as AppAdminBillingInvoicesRouteImport } from './routes/_app.admin.billing.invoices'
import { Route as AppAdminBillingAnalyticsRouteImport } from './routes/_app.admin.billing.analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresRoute = AppStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRoute = AppPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppLotracRoute = AppLotracRouteImport.update({
  id: '/lotrac',
  path: '/lotrac',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanyBillingRoute = AppCompanyBillingRouteImport.update({
  id: '/company/billing',
  path: '/company/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPlansRoute = AppAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrganizationsRoute = AppAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminModulesRoute = AppAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMillsRoute = AppAdminMillsRouteImport.update({
  id: '/mills',
  path: '/mills',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLimitsRoute = AppAdminLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCompaniesRoute = AppAdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminColumnConfigRoute = AppAdminColumnConfigRouteImport.update({
  id: '/column-config',
  path: '/column-config',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBillingRoute = AppAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminArchiveRoute = AppAdminArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBillingSubscriptionsRoute =
  AppAdminBillingSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AppAdminBillingRoute,
  } as any)
const AppAdminBillingPlansRoute = AppAdminBillingPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppAdminBillingRoute,
} as any)
const AppAdminBillingPaymentsRoute = AppAdminBillingPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppAdminBillingRoute,
} as any)
const AppAdminBillingInvoicesRoute = AppAdminBillingInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppAdminBillingRoute,
} as any)
const AppAdminBillingAnalyticsRoute =
  AppAdminBillingAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppAdminBillingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/dispatch': typeof AppDispatchRoute
  '/hr': typeof AppHrRoute
  '/inventory': typeof AppInventoryRoute
  '/lotrac': typeof AppLotracRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/masters': typeof AppMastersRoute
  '/payroll': typeof AppPayrollRoute
  '/production': typeof AppProductionRoute
  '/profile': typeof AppProfileRoute
  '/purchase': typeof AppPurchaseRoute
  '/quality': typeof AppQualityRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/stock': typeof AppStockRoute
  '/stores': typeof AppStoresRoute
  '/users': typeof AppUsersRoute
  '/admin/archive': typeof AppAdminArchiveRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/billing': typeof AppAdminBillingRouteWithChildren
  '/admin/column-config': typeof AppAdminColumnConfigRoute
  '/admin/companies': typeof AppAdminCompaniesRoute
  '/admin/limits': typeof AppAdminLimitsRoute
  '/admin/mills': typeof AppAdminMillsRoute
  '/admin/modules': typeof AppAdminModulesRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/admin/plans': typeof AppAdminPlansRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/company/billing': typeof AppCompanyBillingRoute
  '/admin/billing/analytics': typeof AppAdminBillingAnalyticsRoute
  '/admin/billing/invoices': typeof AppAdminBillingInvoicesRoute
  '/admin/billing/payments': typeof AppAdminBillingPaymentsRoute
  '/admin/billing/plans': typeof AppAdminBillingPlansRoute
  '/admin/billing/subscriptions': typeof AppAdminBillingSubscriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/dispatch': typeof AppDispatchRoute
  '/hr': typeof AppHrRoute
  '/inventory': typeof AppInventoryRoute
  '/lotrac': typeof AppLotracRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/masters': typeof AppMastersRoute
  '/payroll': typeof AppPayrollRoute
  '/production': typeof AppProductionRoute
  '/profile': typeof AppProfileRoute
  '/purchase': typeof AppPurchaseRoute
  '/quality': typeof AppQualityRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/stock': typeof AppStockRoute
  '/stores': typeof AppStoresRoute
  '/users': typeof AppUsersRoute
  '/admin/archive': typeof AppAdminArchiveRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/billing': typeof AppAdminBillingRouteWithChildren
  '/admin/column-config': typeof AppAdminColumnConfigRoute
  '/admin/companies': typeof AppAdminCompaniesRoute
  '/admin/limits': typeof AppAdminLimitsRoute
  '/admin/mills': typeof AppAdminMillsRoute
  '/admin/modules': typeof AppAdminModulesRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/admin/plans': typeof AppAdminPlansRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/company/billing': typeof AppCompanyBillingRoute
  '/admin/billing/analytics': typeof AppAdminBillingAnalyticsRoute
  '/admin/billing/invoices': typeof AppAdminBillingInvoicesRoute
  '/admin/billing/payments': typeof AppAdminBillingPaymentsRoute
  '/admin/billing/plans': typeof AppAdminBillingPlansRoute
  '/admin/billing/subscriptions': typeof AppAdminBillingSubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dispatch': typeof AppDispatchRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/lotrac': typeof AppLotracRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/masters': typeof AppMastersRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/purchase': typeof AppPurchaseRoute
  '/_app/quality': typeof AppQualityRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/stores': typeof AppStoresRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/admin/archive': typeof AppAdminArchiveRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/billing': typeof AppAdminBillingRouteWithChildren
  '/_app/admin/column-config': typeof AppAdminColumnConfigRoute
  '/_app/admin/companies': typeof AppAdminCompaniesRoute
  '/_app/admin/limits': typeof AppAdminLimitsRoute
  '/_app/admin/mills': typeof AppAdminMillsRoute
  '/_app/admin/modules': typeof AppAdminModulesRoute
  '/_app/admin/organizations': typeof AppAdminOrganizationsRoute
  '/_app/admin/plans': typeof AppAdminPlansRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/company/billing': typeof AppCompanyBillingRoute
  '/_app/admin/billing/analytics': typeof AppAdminBillingAnalyticsRoute
  '/_app/admin/billing/invoices': typeof AppAdminBillingInvoicesRoute
  '/_app/admin/billing/payments': typeof AppAdminBillingPaymentsRoute
  '/_app/admin/billing/plans': typeof AppAdminBillingPlansRoute
  '/_app/admin/billing/subscriptions': typeof AppAdminBillingSubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/accounts'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/dispatch'
    | '/hr'
    | '/inventory'
    | '/lotrac'
    | '/maintenance'
    | '/masters'
    | '/payroll'
    | '/production'
    | '/profile'
    | '/purchase'
    | '/quality'
    | '/reports'
    | '/sales'
    | '/stock'
    | '/stores'
    | '/users'
    | '/admin/archive'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/column-config'
    | '/admin/companies'
    | '/admin/limits'
    | '/admin/mills'
    | '/admin/modules'
    | '/admin/organizations'
    | '/admin/plans'
    | '/admin/users'
    | '/company/billing'
    | '/admin/billing/analytics'
    | '/admin/billing/invoices'
    | '/admin/billing/payments'
    | '/admin/billing/plans'
    | '/admin/billing/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/accounts'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/dispatch'
    | '/hr'
    | '/inventory'
    | '/lotrac'
    | '/maintenance'
    | '/masters'
    | '/payroll'
    | '/production'
    | '/profile'
    | '/purchase'
    | '/quality'
    | '/reports'
    | '/sales'
    | '/stock'
    | '/stores'
    | '/users'
    | '/admin/archive'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/column-config'
    | '/admin/companies'
    | '/admin/limits'
    | '/admin/mills'
    | '/admin/modules'
    | '/admin/organizations'
    | '/admin/plans'
    | '/admin/users'
    | '/company/billing'
    | '/admin/billing/analytics'
    | '/admin/billing/invoices'
    | '/admin/billing/payments'
    | '/admin/billing/plans'
    | '/admin/billing/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/login'
    | '/_app/accounts'
    | '/_app/admin'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/dispatch'
    | '/_app/hr'
    | '/_app/inventory'
    | '/_app/lotrac'
    | '/_app/maintenance'
    | '/_app/masters'
    | '/_app/payroll'
    | '/_app/production'
    | '/_app/profile'
    | '/_app/purchase'
    | '/_app/quality'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/stock'
    | '/_app/stores'
    | '/_app/users'
    | '/_app/admin/archive'
    | '/_app/admin/audit'
    | '/_app/admin/billing'
    | '/_app/admin/column-config'
    | '/_app/admin/companies'
    | '/_app/admin/limits'
    | '/_app/admin/mills'
    | '/_app/admin/modules'
    | '/_app/admin/organizations'
    | '/_app/admin/plans'
    | '/_app/admin/users'
    | '/_app/company/billing'
    | '/_app/admin/billing/analytics'
    | '/_app/admin/billing/invoices'
    | '/_app/admin/billing/payments'
    | '/_app/admin/billing/plans'
    | '/_app/admin/billing/subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores': {
      id: '/_app/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AppStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase': {
      id: '/_app/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof AppPurchaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters': {
      id: '/_app/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lotrac': {
      id: '/_app/lotrac'
      path: '/lotrac'
      fullPath: '/lotrac'
      preLoaderRoute: typeof AppLotracRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispatch': {
      id: '/_app/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/company/billing': {
      id: '/_app/company/billing'
      path: '/company/billing'
      fullPath: '/company/billing'
      preLoaderRoute: typeof AppCompanyBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/plans': {
      id: '/_app/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AppAdminPlansRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/organizations': {
      id: '/_app/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AppAdminOrganizationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/modules': {
      id: '/_app/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AppAdminModulesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/mills': {
      id: '/_app/admin/mills'
      path: '/mills'
      fullPath: '/admin/mills'
      preLoaderRoute: typeof AppAdminMillsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/limits': {
      id: '/_app/admin/limits'
      path: '/limits'
      fullPath: '/admin/limits'
      preLoaderRoute: typeof AppAdminLimitsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/companies': {
      id: '/_app/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AppAdminCompaniesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/column-config': {
      id: '/_app/admin/column-config'
      path: '/column-config'
      fullPath: '/admin/column-config'
      preLoaderRoute: typeof AppAdminColumnConfigRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/billing': {
      id: '/_app/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AppAdminBillingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/archive': {
      id: '/_app/admin/archive'
      path: '/archive'
      fullPath: '/admin/archive'
      preLoaderRoute: typeof AppAdminArchiveRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/billing/subscriptions': {
      id: '/_app/admin/billing/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/billing/subscriptions'
      preLoaderRoute: typeof AppAdminBillingSubscriptionsRouteImport
      parentRoute: typeof AppAdminBillingRoute
    }
    '/_app/admin/billing/plans': {
      id: '/_app/admin/billing/plans'
      path: '/plans'
      fullPath: '/admin/billing/plans'
      preLoaderRoute: typeof AppAdminBillingPlansRouteImport
      parentRoute: typeof AppAdminBillingRoute
    }
    '/_app/admin/billing/payments': {
      id: '/_app/admin/billing/payments'
      path: '/payments'
      fullPath: '/admin/billing/payments'
      preLoaderRoute: typeof AppAdminBillingPaymentsRouteImport
      parentRoute: typeof AppAdminBillingRoute
    }
    '/_app/admin/billing/invoices': {
      id: '/_app/admin/billing/invoices'
      path: '/invoices'
      fullPath: '/admin/billing/invoices'
      preLoaderRoute: typeof AppAdminBillingInvoicesRouteImport
      parentRoute: typeof AppAdminBillingRoute
    }
    '/_app/admin/billing/analytics': {
      id: '/_app/admin/billing/analytics'
      path: '/analytics'
      fullPath: '/admin/billing/analytics'
      preLoaderRoute: typeof AppAdminBillingAnalyticsRouteImport
      parentRoute: typeof AppAdminBillingRoute
    }
  }
}

interface AppAdminBillingRouteChildren {
  AppAdminBillingAnalyticsRoute: typeof AppAdminBillingAnalyticsRoute
  AppAdminBillingInvoicesRoute: typeof AppAdminBillingInvoicesRoute
  AppAdminBillingPaymentsRoute: typeof AppAdminBillingPaymentsRoute
  AppAdminBillingPlansRoute: typeof AppAdminBillingPlansRoute
  AppAdminBillingSubscriptionsRoute: typeof AppAdminBillingSubscriptionsRoute
}

const AppAdminBillingRouteChildren: AppAdminBillingRouteChildren = {
  AppAdminBillingAnalyticsRoute: AppAdminBillingAnalyticsRoute,
  AppAdminBillingInvoicesRoute: AppAdminBillingInvoicesRoute,
  AppAdminBillingPaymentsRoute: AppAdminBillingPaymentsRoute,
  AppAdminBillingPlansRoute: AppAdminBillingPlansRoute,
  AppAdminBillingSubscriptionsRoute: AppAdminBillingSubscriptionsRoute,
}

const AppAdminBillingRouteWithChildren = AppAdminBillingRoute._addFileChildren(
  AppAdminBillingRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminArchiveRoute: typeof AppAdminArchiveRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBillingRoute: typeof AppAdminBillingRouteWithChildren
  AppAdminColumnConfigRoute: typeof AppAdminColumnConfigRoute
  AppAdminCompaniesRoute: typeof AppAdminCompaniesRoute
  AppAdminLimitsRoute: typeof AppAdminLimitsRoute
  AppAdminMillsRoute: typeof AppAdminMillsRoute
  AppAdminModulesRoute: typeof AppAdminModulesRoute
  AppAdminOrganizationsRoute: typeof AppAdminOrganizationsRoute
  AppAdminPlansRoute: typeof AppAdminPlansRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminArchiveRoute: AppAdminArchiveRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBillingRoute: AppAdminBillingRouteWithChildren,
  AppAdminColumnConfigRoute: AppAdminColumnConfigRoute,
  AppAdminCompaniesRoute: AppAdminCompaniesRoute,
  AppAdminLimitsRoute: AppAdminLimitsRoute,
  AppAdminMillsRoute: AppAdminMillsRoute,
  AppAdminModulesRoute: AppAdminModulesRoute,
  AppAdminOrganizationsRoute: AppAdminOrganizationsRoute,
  AppAdminPlansRoute: AppAdminPlansRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppHrRoute: typeof AppHrRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLotracRoute: typeof AppLotracRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppMastersRoute: typeof AppMastersRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppProductionRoute: typeof AppProductionRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPurchaseRoute: typeof AppPurchaseRoute
  AppQualityRoute: typeof AppQualityRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppStockRoute: typeof AppStockRoute
  AppStoresRoute: typeof AppStoresRoute
  AppUsersRoute: typeof AppUsersRoute
  AppCompanyBillingRoute: typeof AppCompanyBillingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppHrRoute: AppHrRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLotracRoute: AppLotracRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppMastersRoute: AppMastersRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppProductionRoute: AppProductionRoute,
  AppProfileRoute: AppProfileRoute,
  AppPurchaseRoute: AppPurchaseRoute,
  AppQualityRoute: AppQualityRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppStockRoute: AppStockRoute,
  AppStoresRoute: AppStoresRoute,
  AppUsersRoute: AppUsersRoute,
  AppCompanyBillingRoute: AppCompanyBillingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
