/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppStoresRouteImport } from './routes/_app.stores'
import { Route as AppStockRouteImport } from './routes/_app.stock'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRegisterRouteImport } from './routes/_app.register'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppQualityRouteImport } from './routes/_app.quality'
import { Route as AppPurchaseRouteImport } from './routes/_app.purchase'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProductionRouteImport } from './routes/_app.production'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMastersRouteImport } from './routes/_app.masters'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppLotracRouteImport } from './routes/_app.lotrac'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppImportHubRouteImport } from './routes/_app.import-hub'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppHelpCenterRouteImport } from './routes/_app.help-center'
import { Route as AppExecutiveDashboardRouteImport } from './routes/_app.executive-dashboard'
import { Route as AppDispatchRouteImport } from './routes/_app.dispatch'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppProductionLearnerAllocationsRouteImport } from './routes/_app.production.learner-allocations'
import { Route as AppProductionLearnerAllocationRouteImport } from './routes/_app.production.learner-allocation'
import { Route as AppDashboardOwnerRouteImport } from './routes/_app.dashboard.owner'
import { Route as AppCompanySettingsRouteImport } from './routes/_app.company.settings'
import { Route as AppCompanyBillingRouteImport } from './routes/_app.company.billing'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminRolesRouteImport } from './routes/_app.admin.roles'
import { Route as AppAdminIncidentsRouteImport } from './routes/_app.admin.incidents'
import { Route as AppAdminHealthRouteImport } from './routes/_app.admin.health'
import { Route as AppAdminColumnConfigRouteImport } from './routes/_app.admin.column-config'
import { Route as AppAdminBackupsRouteImport } from './routes/_app.admin.backups'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'
import { Route as AppAdminArchiveRouteImport } from './routes/_app.admin.archive'
import { Route as AppAdminApprovalsRouteImport } from './routes/_app.admin.approvals'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app.admin.analytics'
import { Route as AppAdminAlertsRouteImport } from './routes/_app.admin.alerts'
import { Route as AppAdminAlertOpsRouteImport } from './routes/_app.admin.alert-ops'
import { Route as AppProductionLearnerAllocationIdRouteImport } from './routes/_app.production.learner-allocation.$id'
import { Route as AppProductionLearnerAllocationViewIdRouteImport } from './routes/_app.production.learner-allocation-view.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresRoute = AppStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRoute = AppPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppLotracRoute = AppLotracRouteImport.update({
  id: '/lotrac',
  path: '/lotrac',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppImportHubRoute = AppImportHubRouteImport.update({
  id: '/import-hub',
  path: '/import-hub',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpCenterRoute = AppHelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutiveDashboardRoute = AppExecutiveDashboardRouteImport.update({
  id: '/executive-dashboard',
  path: '/executive-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionLearnerAllocationsRoute =
  AppProductionLearnerAllocationsRouteImport.update({
    id: '/learner-allocations',
    path: '/learner-allocations',
    getParentRoute: () => AppProductionRoute,
  } as any)
const AppProductionLearnerAllocationRoute =
  AppProductionLearnerAllocationRouteImport.update({
    id: '/learner-allocation',
    path: '/learner-allocation',
    getParentRoute: () => AppProductionRoute,
  } as any)
const AppDashboardOwnerRoute = AppDashboardOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppCompanySettingsRoute = AppCompanySettingsRouteImport.update({
  id: '/company/settings',
  path: '/company/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanyBillingRoute = AppCompanyBillingRouteImport.update({
  id: '/company/billing',
  path: '/company/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminIncidentsRoute = AppAdminIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHealthRoute = AppAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminColumnConfigRoute = AppAdminColumnConfigRouteImport.update({
  id: '/column-config',
  path: '/column-config',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBackupsRoute = AppAdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminArchiveRoute = AppAdminArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminApprovalsRoute = AppAdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAlertsRoute = AppAdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAlertOpsRoute = AppAdminAlertOpsRouteImport.update({
  id: '/alert-ops',
  path: '/alert-ops',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppProductionLearnerAllocationIdRoute =
  AppProductionLearnerAllocationIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppProductionLearnerAllocationRoute,
  } as any)
const AppProductionLearnerAllocationViewIdRoute =
  AppProductionLearnerAllocationViewIdRouteImport.update({
    id: '/learner-allocation-view/$id',
    path: '/learner-allocation-view/$id',
    getParentRoute: () => AppProductionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/alerts': typeof AppAlertsRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/dispatch': typeof AppDispatchRoute
  '/executive-dashboard': typeof AppExecutiveDashboardRoute
  '/help-center': typeof AppHelpCenterRoute
  '/hr': typeof AppHrRoute
  '/import-hub': typeof AppImportHubRoute
  '/inventory': typeof AppInventoryRoute
  '/lotrac': typeof AppLotracRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/masters': typeof AppMastersRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/payroll': typeof AppPayrollRoute
  '/production': typeof AppProductionRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/purchase': typeof AppPurchaseRoute
  '/quality': typeof AppQualityRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/register': typeof AppRegisterRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/stock': typeof AppStockRoute
  '/stores': typeof AppStoresRoute
  '/users': typeof AppUsersRoute
  '/admin/alert-ops': typeof AppAdminAlertOpsRoute
  '/admin/alerts': typeof AppAdminAlertsRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/archive': typeof AppAdminArchiveRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/backups': typeof AppAdminBackupsRoute
  '/admin/column-config': typeof AppAdminColumnConfigRoute
  '/admin/health': typeof AppAdminHealthRoute
  '/admin/incidents': typeof AppAdminIncidentsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/company/billing': typeof AppCompanyBillingRoute
  '/company/settings': typeof AppCompanySettingsRoute
  '/dashboard/owner': typeof AppDashboardOwnerRoute
  '/production/learner-allocation': typeof AppProductionLearnerAllocationRouteWithChildren
  '/production/learner-allocations': typeof AppProductionLearnerAllocationsRoute
  '/production/learner-allocation-view/$id': typeof AppProductionLearnerAllocationViewIdRoute
  '/production/learner-allocation/$id': typeof AppProductionLearnerAllocationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/alerts': typeof AppAlertsRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/dispatch': typeof AppDispatchRoute
  '/executive-dashboard': typeof AppExecutiveDashboardRoute
  '/help-center': typeof AppHelpCenterRoute
  '/hr': typeof AppHrRoute
  '/import-hub': typeof AppImportHubRoute
  '/inventory': typeof AppInventoryRoute
  '/lotrac': typeof AppLotracRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/masters': typeof AppMastersRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/payroll': typeof AppPayrollRoute
  '/production': typeof AppProductionRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/purchase': typeof AppPurchaseRoute
  '/quality': typeof AppQualityRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/register': typeof AppRegisterRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/stock': typeof AppStockRoute
  '/stores': typeof AppStoresRoute
  '/users': typeof AppUsersRoute
  '/admin/alert-ops': typeof AppAdminAlertOpsRoute
  '/admin/alerts': typeof AppAdminAlertsRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/archive': typeof AppAdminArchiveRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/backups': typeof AppAdminBackupsRoute
  '/admin/column-config': typeof AppAdminColumnConfigRoute
  '/admin/health': typeof AppAdminHealthRoute
  '/admin/incidents': typeof AppAdminIncidentsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/company/billing': typeof AppCompanyBillingRoute
  '/company/settings': typeof AppCompanySettingsRoute
  '/dashboard/owner': typeof AppDashboardOwnerRoute
  '/production/learner-allocation': typeof AppProductionLearnerAllocationRouteWithChildren
  '/production/learner-allocations': typeof AppProductionLearnerAllocationsRoute
  '/production/learner-allocation-view/$id': typeof AppProductionLearnerAllocationViewIdRoute
  '/production/learner-allocation/$id': typeof AppProductionLearnerAllocationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/dispatch': typeof AppDispatchRoute
  '/_app/executive-dashboard': typeof AppExecutiveDashboardRoute
  '/_app/help-center': typeof AppHelpCenterRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/import-hub': typeof AppImportHubRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/lotrac': typeof AppLotracRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/masters': typeof AppMastersRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/production': typeof AppProductionRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/purchase': typeof AppPurchaseRoute
  '/_app/quality': typeof AppQualityRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/stores': typeof AppStoresRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/admin/alert-ops': typeof AppAdminAlertOpsRoute
  '/_app/admin/alerts': typeof AppAdminAlertsRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/approvals': typeof AppAdminApprovalsRoute
  '/_app/admin/archive': typeof AppAdminArchiveRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/backups': typeof AppAdminBackupsRoute
  '/_app/admin/column-config': typeof AppAdminColumnConfigRoute
  '/_app/admin/health': typeof AppAdminHealthRoute
  '/_app/admin/incidents': typeof AppAdminIncidentsRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/company/billing': typeof AppCompanyBillingRoute
  '/_app/company/settings': typeof AppCompanySettingsRoute
  '/_app/dashboard/owner': typeof AppDashboardOwnerRoute
  '/_app/production/learner-allocation': typeof AppProductionLearnerAllocationRouteWithChildren
  '/_app/production/learner-allocations': typeof AppProductionLearnerAllocationsRoute
  '/_app/production/learner-allocation-view/$id': typeof AppProductionLearnerAllocationViewIdRoute
  '/_app/production/learner-allocation/$id': typeof AppProductionLearnerAllocationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/accounts'
    | '/admin'
    | '/alerts'
    | '/audit'
    | '/dashboard'
    | '/dispatch'
    | '/executive-dashboard'
    | '/help-center'
    | '/hr'
    | '/import-hub'
    | '/inventory'
    | '/lotrac'
    | '/maintenance'
    | '/masters'
    | '/notifications'
    | '/onboarding'
    | '/payroll'
    | '/production'
    | '/profile'
    | '/purchase'
    | '/quality'
    | '/recommendations'
    | '/register'
    | '/reports'
    | '/sales'
    | '/stock'
    | '/stores'
    | '/users'
    | '/admin/alert-ops'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/archive'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/column-config'
    | '/admin/health'
    | '/admin/incidents'
    | '/admin/roles'
    | '/admin/users'
    | '/company/billing'
    | '/company/settings'
    | '/dashboard/owner'
    | '/production/learner-allocation'
    | '/production/learner-allocations'
    | '/production/learner-allocation-view/$id'
    | '/production/learner-allocation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/accounts'
    | '/admin'
    | '/alerts'
    | '/audit'
    | '/dashboard'
    | '/dispatch'
    | '/executive-dashboard'
    | '/help-center'
    | '/hr'
    | '/import-hub'
    | '/inventory'
    | '/lotrac'
    | '/maintenance'
    | '/masters'
    | '/notifications'
    | '/onboarding'
    | '/payroll'
    | '/production'
    | '/profile'
    | '/purchase'
    | '/quality'
    | '/recommendations'
    | '/register'
    | '/reports'
    | '/sales'
    | '/stock'
    | '/stores'
    | '/users'
    | '/admin/alert-ops'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/archive'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/column-config'
    | '/admin/health'
    | '/admin/incidents'
    | '/admin/roles'
    | '/admin/users'
    | '/company/billing'
    | '/company/settings'
    | '/dashboard/owner'
    | '/production/learner-allocation'
    | '/production/learner-allocations'
    | '/production/learner-allocation-view/$id'
    | '/production/learner-allocation/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/_app/accounts'
    | '/_app/admin'
    | '/_app/alerts'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/dispatch'
    | '/_app/executive-dashboard'
    | '/_app/help-center'
    | '/_app/hr'
    | '/_app/import-hub'
    | '/_app/inventory'
    | '/_app/lotrac'
    | '/_app/maintenance'
    | '/_app/masters'
    | '/_app/notifications'
    | '/_app/onboarding'
    | '/_app/payroll'
    | '/_app/production'
    | '/_app/profile'
    | '/_app/purchase'
    | '/_app/quality'
    | '/_app/recommendations'
    | '/_app/register'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/stock'
    | '/_app/stores'
    | '/_app/users'
    | '/_app/admin/alert-ops'
    | '/_app/admin/alerts'
    | '/_app/admin/analytics'
    | '/_app/admin/approvals'
    | '/_app/admin/archive'
    | '/_app/admin/audit'
    | '/_app/admin/backups'
    | '/_app/admin/column-config'
    | '/_app/admin/health'
    | '/_app/admin/incidents'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/company/billing'
    | '/_app/company/settings'
    | '/_app/dashboard/owner'
    | '/_app/production/learner-allocation'
    | '/_app/production/learner-allocations'
    | '/_app/production/learner-allocation-view/$id'
    | '/_app/production/learner-allocation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores': {
      id: '/_app/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AppStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase': {
      id: '/_app/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof AppPurchaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters': {
      id: '/_app/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lotrac': {
      id: '/_app/lotrac'
      path: '/lotrac'
      fullPath: '/lotrac'
      preLoaderRoute: typeof AppLotracRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-hub': {
      id: '/_app/import-hub'
      path: '/import-hub'
      fullPath: '/import-hub'
      preLoaderRoute: typeof AppImportHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help-center': {
      id: '/_app/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AppHelpCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/executive-dashboard': {
      id: '/_app/executive-dashboard'
      path: '/executive-dashboard'
      fullPath: '/executive-dashboard'
      preLoaderRoute: typeof AppExecutiveDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispatch': {
      id: '/_app/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/learner-allocations': {
      id: '/_app/production/learner-allocations'
      path: '/learner-allocations'
      fullPath: '/production/learner-allocations'
      preLoaderRoute: typeof AppProductionLearnerAllocationsRouteImport
      parentRoute: typeof AppProductionRoute
    }
    '/_app/production/learner-allocation': {
      id: '/_app/production/learner-allocation'
      path: '/learner-allocation'
      fullPath: '/production/learner-allocation'
      preLoaderRoute: typeof AppProductionLearnerAllocationRouteImport
      parentRoute: typeof AppProductionRoute
    }
    '/_app/dashboard/owner': {
      id: '/_app/dashboard/owner'
      path: '/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof AppDashboardOwnerRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/company/settings': {
      id: '/_app/company/settings'
      path: '/company/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof AppCompanySettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/company/billing': {
      id: '/_app/company/billing'
      path: '/company/billing'
      fullPath: '/company/billing'
      preLoaderRoute: typeof AppCompanyBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/incidents': {
      id: '/_app/admin/incidents'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AppAdminIncidentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/health': {
      id: '/_app/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AppAdminHealthRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/column-config': {
      id: '/_app/admin/column-config'
      path: '/column-config'
      fullPath: '/admin/column-config'
      preLoaderRoute: typeof AppAdminColumnConfigRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/backups': {
      id: '/_app/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AppAdminBackupsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/archive': {
      id: '/_app/admin/archive'
      path: '/archive'
      fullPath: '/admin/archive'
      preLoaderRoute: typeof AppAdminArchiveRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/approvals': {
      id: '/_app/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AppAdminApprovalsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/alerts': {
      id: '/_app/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AppAdminAlertsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/alert-ops': {
      id: '/_app/admin/alert-ops'
      path: '/alert-ops'
      fullPath: '/admin/alert-ops'
      preLoaderRoute: typeof AppAdminAlertOpsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/production/learner-allocation/$id': {
      id: '/_app/production/learner-allocation/$id'
      path: '/$id'
      fullPath: '/production/learner-allocation/$id'
      preLoaderRoute: typeof AppProductionLearnerAllocationIdRouteImport
      parentRoute: typeof AppProductionLearnerAllocationRoute
    }
    '/_app/production/learner-allocation-view/$id': {
      id: '/_app/production/learner-allocation-view/$id'
      path: '/learner-allocation-view/$id'
      fullPath: '/production/learner-allocation-view/$id'
      preLoaderRoute: typeof AppProductionLearnerAllocationViewIdRouteImport
      parentRoute: typeof AppProductionRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAlertOpsRoute: typeof AppAdminAlertOpsRoute
  AppAdminAlertsRoute: typeof AppAdminAlertsRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminApprovalsRoute: typeof AppAdminApprovalsRoute
  AppAdminArchiveRoute: typeof AppAdminArchiveRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBackupsRoute: typeof AppAdminBackupsRoute
  AppAdminColumnConfigRoute: typeof AppAdminColumnConfigRoute
  AppAdminHealthRoute: typeof AppAdminHealthRoute
  AppAdminIncidentsRoute: typeof AppAdminIncidentsRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAlertOpsRoute: AppAdminAlertOpsRoute,
  AppAdminAlertsRoute: AppAdminAlertsRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminApprovalsRoute: AppAdminApprovalsRoute,
  AppAdminArchiveRoute: AppAdminArchiveRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBackupsRoute: AppAdminBackupsRoute,
  AppAdminColumnConfigRoute: AppAdminColumnConfigRoute,
  AppAdminHealthRoute: AppAdminHealthRoute,
  AppAdminIncidentsRoute: AppAdminIncidentsRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppDashboardRouteChildren {
  AppDashboardOwnerRoute: typeof AppDashboardOwnerRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardOwnerRoute: AppDashboardOwnerRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppProductionLearnerAllocationRouteChildren {
  AppProductionLearnerAllocationIdRoute: typeof AppProductionLearnerAllocationIdRoute
}

const AppProductionLearnerAllocationRouteChildren: AppProductionLearnerAllocationRouteChildren =
  {
    AppProductionLearnerAllocationIdRoute:
      AppProductionLearnerAllocationIdRoute,
  }

const AppProductionLearnerAllocationRouteWithChildren =
  AppProductionLearnerAllocationRoute._addFileChildren(
    AppProductionLearnerAllocationRouteChildren,
  )

interface AppProductionRouteChildren {
  AppProductionLearnerAllocationRoute: typeof AppProductionLearnerAllocationRouteWithChildren
  AppProductionLearnerAllocationsRoute: typeof AppProductionLearnerAllocationsRoute
  AppProductionLearnerAllocationViewIdRoute: typeof AppProductionLearnerAllocationViewIdRoute
}

const AppProductionRouteChildren: AppProductionRouteChildren = {
  AppProductionLearnerAllocationRoute:
    AppProductionLearnerAllocationRouteWithChildren,
  AppProductionLearnerAllocationsRoute: AppProductionLearnerAllocationsRoute,
  AppProductionLearnerAllocationViewIdRoute:
    AppProductionLearnerAllocationViewIdRoute,
}

const AppProductionRouteWithChildren = AppProductionRoute._addFileChildren(
  AppProductionRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAlertsRoute: typeof AppAlertsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppDispatchRoute: typeof AppDispatchRoute
  AppExecutiveDashboardRoute: typeof AppExecutiveDashboardRoute
  AppHelpCenterRoute: typeof AppHelpCenterRoute
  AppHrRoute: typeof AppHrRoute
  AppImportHubRoute: typeof AppImportHubRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLotracRoute: typeof AppLotracRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppMastersRoute: typeof AppMastersRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppProductionRoute: typeof AppProductionRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppPurchaseRoute: typeof AppPurchaseRoute
  AppQualityRoute: typeof AppQualityRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppStockRoute: typeof AppStockRoute
  AppStoresRoute: typeof AppStoresRoute
  AppUsersRoute: typeof AppUsersRoute
  AppCompanyBillingRoute: typeof AppCompanyBillingRoute
  AppCompanySettingsRoute: typeof AppCompanySettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAlertsRoute: AppAlertsRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppDispatchRoute: AppDispatchRoute,
  AppExecutiveDashboardRoute: AppExecutiveDashboardRoute,
  AppHelpCenterRoute: AppHelpCenterRoute,
  AppHrRoute: AppHrRoute,
  AppImportHubRoute: AppImportHubRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLotracRoute: AppLotracRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppMastersRoute: AppMastersRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppProductionRoute: AppProductionRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppPurchaseRoute: AppPurchaseRoute,
  AppQualityRoute: AppQualityRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppStockRoute: AppStockRoute,
  AppStoresRoute: AppStoresRoute,
  AppUsersRoute: AppUsersRoute,
  AppCompanyBillingRoute: AppCompanyBillingRoute,
  AppCompanySettingsRoute: AppCompanySettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
