/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppStoresRouteImport } from './routes/_app.stores'
import { Route as AppStockRouteImport } from './routes/_app.stock'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppQualityRouteImport } from './routes/_app.quality'
import { Route as AppPurchaseRouteImport } from './routes/_app.purchase'
import { Route as AppProductionRouteImport } from './routes/_app.production'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppMastersRouteImport } from './routes/_app.masters'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppLotracRouteImport } from './routes/_app.lotrac'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppDispatchRouteImport } from './routes/_app.dispatch'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppAdminColumnConfigRouteImport } from './routes/_app.admin.column-config'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresRoute = AppStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRoute = AppPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppLotracRoute = AppLotracRouteImport.update({
  id: '/lotrac',
  path: '/lotrac',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminColumnConfigRoute = AppAdminColumnConfigRouteImport.update({
  id: '/admin/column-config',
  path: '/admin/column-config',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/admin': typeof AppAdminRoute
  '/admin/column-config': typeof AppAdminColumnConfigRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/dispatch': typeof AppDispatchRoute
  '/hr': typeof AppHrRoute
  '/inventory': typeof AppInventoryRoute
  '/lotrac': typeof AppLotracRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/masters': typeof AppMastersRoute
  '/payroll': typeof AppPayrollRoute
  '/production': typeof AppProductionRoute
  '/purchase': typeof AppPurchaseRoute
  '/quality': typeof AppQualityRoute
  '/reports': typeof AppReportsRoute
  '/stock': typeof AppStockRoute
  '/stores': typeof AppStoresRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRoute
  '/admin': typeof AppAdminRoute
  '/admin/column-config': typeof AppAdminColumnConfigRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/dispatch': typeof AppDispatchRoute
  '/hr': typeof AppHrRoute
  '/inventory': typeof AppInventoryRoute
  '/lotrac': typeof AppLotracRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/masters': typeof AppMastersRoute
  '/payroll': typeof AppPayrollRoute
  '/production': typeof AppProductionRoute
  '/purchase': typeof AppPurchaseRoute
  '/quality': typeof AppQualityRoute
  '/reports': typeof AppReportsRoute
  '/stock': typeof AppStockRoute
  '/stores': typeof AppStoresRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/admin/column-config': typeof AppAdminColumnConfigRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dispatch': typeof AppDispatchRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/lotrac': typeof AppLotracRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/masters': typeof AppMastersRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/purchase': typeof AppPurchaseRoute
  '/_app/quality': typeof AppQualityRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/stores': typeof AppStoresRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/accounts'
    | '/admin'
    | '/admin/column-config'
    | '/audit'
    | '/dashboard'
    | '/dispatch'
    | '/hr'
    | '/inventory'
    | '/lotrac'
    | '/maintenance'
    | '/masters'
    | '/payroll'
    | '/production'
    | '/purchase'
    | '/quality'
    | '/reports'
    | '/stock'
    | '/stores'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/accounts'
    | '/admin'
    | '/admin/column-config'
    | '/audit'
    | '/dashboard'
    | '/dispatch'
    | '/hr'
    | '/inventory'
    | '/lotrac'
    | '/maintenance'
    | '/masters'
    | '/payroll'
    | '/production'
    | '/purchase'
    | '/quality'
    | '/reports'
    | '/stock'
    | '/stores'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/login'
    | '/_app/accounts'
    | '/_app/admin'
    | '/_app/admin/column-config'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/dispatch'
    | '/_app/hr'
    | '/_app/inventory'
    | '/_app/lotrac'
    | '/_app/maintenance'
    | '/_app/masters'
    | '/_app/payroll'
    | '/_app/production'
    | '/_app/purchase'
    | '/_app/quality'
    | '/_app/reports'
    | '/_app/stock'
    | '/_app/stores'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores': {
      id: '/_app/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AppStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase': {
      id: '/_app/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof AppPurchaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters': {
      id: '/_app/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lotrac': {
      id: '/_app/lotrac'
      path: '/lotrac'
      fullPath: '/lotrac'
      preLoaderRoute: typeof AppLotracRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispatch': {
      id: '/_app/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/column-config': {
      id: '/_app/admin/column-config'
      path: '/admin/column-config'
      fullPath: '/admin/column-config'
      preLoaderRoute: typeof AppAdminColumnConfigRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAdminColumnConfigRoute: typeof AppAdminColumnConfigRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppHrRoute: typeof AppHrRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLotracRoute: typeof AppLotracRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppMastersRoute: typeof AppMastersRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppProductionRoute: typeof AppProductionRoute
  AppPurchaseRoute: typeof AppPurchaseRoute
  AppQualityRoute: typeof AppQualityRoute
  AppReportsRoute: typeof AppReportsRoute
  AppStockRoute: typeof AppStockRoute
  AppStoresRoute: typeof AppStoresRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAdminRoute: AppAdminRoute,
  AppAdminColumnConfigRoute: AppAdminColumnConfigRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppHrRoute: AppHrRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLotracRoute: AppLotracRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppMastersRoute: AppMastersRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppProductionRoute: AppProductionRoute,
  AppPurchaseRoute: AppPurchaseRoute,
  AppQualityRoute: AppQualityRoute,
  AppReportsRoute: AppReportsRoute,
  AppStockRoute: AppStockRoute,
  AppStoresRoute: AppStoresRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
